LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'demo'
OUTPUT_DIR: 'experiments/'
NUM_WORKERS: 0
MODEL_CONFIG: 'configs/yamls/model_base.yaml'
FLIP_EVAL: TRUE

TRAIN:
  STAGE: 'stage2'
  CHECKPOINT: 'checkpoints/wham_stage2.pth.tar'

MODEL:
  BACKBONE: 'vit'